
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.gtceu]
			rubber = false

		[types.wood_type.tfc]
			acacia = true
			ash = true
			aspen = true
			birch = true
			blackwood = true
			chestnut = true
			douglas_fir = true
			hickory = true
			kapok = true
			mangrove = true
			maple = true
			oak = true
			palm = true
			pine = true
			rosewood = true
			sequoia = true
			spruce = true
			sycamore = true
			white_cedar = true
			willow = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.aether]
			skyroot = true

	[types.leaves_type]

		[types.leaves_type.gtceu]
			rubber = false

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.dtarsnouveau]
			red_archwood = true
			purple_archwood = true
			green_archwood = true
			blue_archwood = true

		[types.leaves_type.aether]
			golden_oak = true
			holiday = true
			decorated_holiday = true
			crystal = true
			crystal_fruit = true
			skyroot = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.create]
			window_pane = true
			window = true

